
server:
  port: 1111
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/javabatch
    username: root
    password: Ambika@91
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql: true
    
#spring.security.user.name
#spring.security.user.password


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      base-path: /myactuator
      
      
  info:
    env:
      enabled: true
 
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      
#info:
#  createdBy: Ambika
#  modifiedBy: 22ndjune2022
  

 
  
logging:
  level:
    com:
     zensar: debug
  
        