server:
  port: 8688
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:7780/javabatch
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql: true
      
      
Management:
 endpoints:
  web:
   base-path: /myactuator    
   
  
   exposure:
    include:
     - "*"   