server:
  port: 9090
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:2222/javabatch
    username: root
 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      
      
